# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: code_quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install prospector[with_bandit]
        pip install prospector[with_mypy]
        pip install prospector[with_pyroma]
        pip install prospector[with_vulture]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Lint with prospector
      working-directory: ./
      run: |
        prospector hisim/utils.py
        prospector hisim/simulator.py
        prospector hisim/simulationparameters.py
        prospector hisim/postprocessingoptions.py
        prospector hisim/log.py
        prospector hisim/loadtypes.py
        prospector hisim/hisim_main.py
        
        

#        # pylint hisim/simulator.py --rcfile=hisim_pylint_config.rc
#        # flake8 hisim/simulator.py --max-line-length 150
#        # pycodestyle hisim/simulator.py --max-line-length 150
