# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: eradicate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8-eradicate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Lint with flake8
      working-directory: ./
      run: |
        flake8 hisim/simulator.py --count --select=E9,F63,F7,F82,E800 --show-source --statistics
        flake8 hisim/simulationparameters.py --count --select=E9,F63,F7,F82,E800 --show-source --statistics
        flake8 hisim/postprocessingoptions.py --count --select=E9,F63,F7,F82,E800 --show-source --statistics
        flake8 hisim/log.py --count --select=E9,F63,F7,F82,E800 --show-source --statistics
        flake8 hisim/loadtypes.py --count --select=E9,F63,F7,F82,E800 --show-source --statistics
        flake8 hisim/hisim_with_profiler.py --count --select=E9,F63,F7,F82,E800 --show-source --statistics
        flake8 hisim/hisim_main.py --count --select=E9,F63,F7,F82,E800 --show-source --statistics
        flake8 hisim/project_code_overview_generator.py --count --select=E9,F63,F7,F82,E800 --show-source --statistics

# reenable once all source files are fixed and no more commented out code is spread all over
# flake8 . --count --select=E9,F63,F7,F82,E800 --show-source --statistics
    #    # stop the build if there are Python syntax errors or undefined names
       
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
