name: Mypy

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install Dependencies
      run: |
        pip install mypy
    - name: mypy
      run: |
        mypy -p hisim --config-file mypy.ini
        mypy --config-file mypy_moderate.ini examples/
        mypy --config-file mypy_moderate.ini tests/
